export { Persik } from './Persik';
export { Home } from './Home';
export { Profile } from './profile';
export {Phases} from './Phases';
export { OnePage } from './1page';
export { TwoPage } from './2page';
export { ThreePage } from './3page';
export { FourPage } from './4page';
export { FivePage } from './5page';
export { SixPage } from './6page';
export { SevenPage } from './7page';
export { EightPage } from './8page';
export { NinePage } from './9page';
export { TenPage } from './10page';
export { ElevenPage } from './11page';
export {Modals} from '../ModalRoot';
export {AppTabs} from './AppTabs';
export {ReportPage} from './Report';
export {FaqOne} from './FaqOne';
export {FaqTwo} from './FaqTwo';
export {FaqThree} from './FaqThree';
export {FaqFour} from './FaqFour';
export {FaqFive} from './FaqFive';
export {Chat} from './chat';